version: '3.8'

services:
  financial-demo:
    image: financial-demo
    build:
      context: ./
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    user: "${UID}:${GID}"
    volumes:
      - ./:/app

