version: '3.8'

services:
  server:
    command: "run actions --port 5056"
    image: rasa/rasa:2.6.0-full
    stdin_open: true
    ports:
      - 5056:5056
    tty: true
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./:/app

  financial-demo:
    command: "shell"
    image: rasa/rasa:2.6.0-full
    stdin_open: true
    ports:
      - 8080:5055
    tty: true
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./:/app

